name: Build and Deploy coqdoc

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build-js:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Build coqdoc
        uses: coq-community/docker-coq-action@v1
        with:
          custom_image: 'coqorg/coq:dev'
          custom_script: |
            {{before_install}}
            startGroup "Build aac-tactics dependencies"
              opam pin add -n -y -k path coq-aac-tactics .
              opam update -y
              opam install -y -j "$(nproc)" coq-aac-tactics --deps-only
            endGroup
            startGroup "Add permissions"
              sudo chown -R coq:coq .
            endGroup
            startGroup "Build coqdoc"
              make -j "$(nproc)" coqdoc
            endGroup

      - name: Revert Coq user permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

      - name: Copy HTML and CSS and JavaScript
        run: |
          mkdir public
          cp -r resources/index.html docs/ public/

      - name: Deploy to GitHub pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: public
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
