name: Docker CI

on:
  push:
    branches:
      - v8.18
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-aac-tactics.opam'
          custom_image: ${{ matrix.image }}
          before_install: |
            startGroup "Print opam config and unpin dune"
              opam config list; opam repo list; opam list; opam pin remove coq-core coq-stdlib coqide-server coq -y
            endGroup

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
